### PR TITLE
Fix a BC introduced in latest version of grpc 

### PR DESCRIPTION
**Pull request by macnibblet**
fix: grpc broke BC in the latest version 1.53.0

### CODE REVIEW

**Comment by phildebrand** [comment]
Nice patch, we also encountered this issue today. Hopefully it will be merged soon. You might also want to update the "USAGE" in  `README.md` with the new `v4` version

**Comment by alanprot** [comment]
There is way more thing broken when updating to 1.53.0, like this line:

https://github.com/sercand/kuberesolver/blob/4bdf89af1056edb2078fed38f3addc53368bc921/builder_test.go#L90

**Comment by dannyskoog** [comment]
@sercand Could you please have a look at this PR? Appreciate it 👍

**Comment by wyattanderson** [comment]
This MR is somewhat broken in its current form. I'm working on a new one that fixes the tests, etc. and hope to post it up today.

**Comment by wyattanderson** [comment]
https://github.com/sercand/kuberesolver/pull/36

**Comment by sercand** [comment]
Sorry folks, I completely missed all the PRs last two weeks. There are 3 PRs for the same issue and I will probably go with https://github.com/sercand/kuberesolver/pull/36 or https://github.com/sercand/kuberesolver/pull/37

**Comment by macnibblet** [comment]
@wyattanderson thanks, covid knocked me out and forgot about this!

**Pull request closed without merging**
