### PR TITLE
include add'l metadata in resolved addresses

### PR DESCRIPTION
**Pull request by jhump**
This allows for implementing custom balancers that might be interested in additional information about the target endpoints.

This adds the endpoint reference (typically a pod reference) and its labels to the `Attributes` field of the resulting `resolver.Address` values.

### CODE REVIEW

**Comment by jhump** [comment]
@sercand, any chance you'd accept a small patch?

**Comment by sercand** [comment]
@jhump Thanks for the PR

**Comment by jhump** [comment]
@sercand, looks like this can tickle issues in gRPC, where typical balancer implementations will churn connections (e.g. close all connections and re-establish all new ones). I've filed https://github.com/grpc/grpc-go/issues/3611.

Not sure if you want to revert this PR until that is remedied or just hold off on a release. But I figured I should let you know. (This change worked great in test environments; but it just hit our production environment yesterday, where the scale of connection churn started causing some issues 😦).

**Comment by lvyijin** [comment]
Hi，@sercand, we encountered the same problem as Jhump. And I would like to konw why changed Metadata interface{} in v1.19.1 to Attributes *attributes.Attributes in v1.26.0.

**Comment by sercand** [comment]
I just reverted the changes. I haven't upgraded our gRPC version to the latest that's why I missed the problem. I will look for this as soon as possible.

**Pull request merged**
